# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/layout/layout.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==layout || ORIG_REF_NAME==layout} -quiet] -quiet

# IP: bd/layout/ip/layout_romModule_0_0/layout_romModule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==layout_romModule_0_0 || ORIG_REF_NAME==layout_romModule_0_0} -quiet] -quiet

# IP: bd/layout/ip/layout_ledOutput_0_0/layout_ledOutput_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==layout_ledOutput_0_0 || ORIG_REF_NAME==layout_ledOutput_0_0} -quiet] -quiet

# IP: bd/layout/ip/layout_testModule_0_0/layout_testModule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==layout_testModule_0_0 || ORIG_REF_NAME==layout_testModule_0_0} -quiet] -quiet

# XDC: /home/elias/Desktop/Projects/simpleCPU/simpleCPU.gen/sources_1/bd/layout/layout_ooc.xdc
